import type { Metadata } from "next";
import { Poppins, Inter, Rajdhani } from "next/font/google";
import "../styles/globals.css";
import "../styles/custom.css";
import Providers from "./providers";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--font-robot",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${inter.variable} ${rajdhani.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        <Script src="/process.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
